image: docker

services:
    - docker:dind

stages:
    - test
    - deploy

test:
    state: test
    only:
        - develop
        - master
    script:
        - echo run tests in this section
step-deploy-prod:
    stage: deploy
    only:
        - master
    script:
        - sudo apt-get install -y python-pip
        - pip install docker-compose
        - docker-compose up -d --build
    environment: master
    when: manual
