version: "3.7"

services:
  vue:
    image: node:12-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./frontend:/app
    container_name: frontend
    networks:
      - frontend-network

  database:
    image: mysql:5.7
    environment:
      MYSQL_USER: ssafy
      MYSQL_DATABASE: ssafy
      MYSQL_PASSWORD: ssafy
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./database/spring_social/:/var/lib/mysql"
    ports:
      - "3306:3306"
    container_name: plee_mysql
    networks:
      - backend-network

  spring-boot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - "8080:8080"
      - "5005:5005"
    container_name: backend
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://plee_mysql:3306/spring_social?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ssafy
      SPRING_DATASOURCE_PASSWORD: ssafy
    networks:
      - backend-network
      - frontend-network

networks:
  backend-network:
  frontend-network:
