version: "3"
services:
  db: # 서비스 명
    image: mysql:5.7 # 사용할 이미지
    restart: always
    command: --lower_case_table_names=1
    container_name: mysql # 컨테이너 이름 설정
    ports:
        - "3307:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
        - MYSQL_DATABASE=ssafy
        - MYSQL_ROOT_PASSWORD=ssafy  # MYSQL 패스워드 설정 옵션
        - TZ=Asia/Seoul
    command: # 명령어 실행
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
    volumes:
        - /Users/Shared/data/mysql-test:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:5001"
    depends_on:
      - postgres
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:5002"
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: proxy
    build: ./.nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443